# airlines.py

airlines = [
    "Aeroflot",
    "Emirates",
    "Lufthansa",
    "Delta Air Lines",
    "British Airways",
    "United Airlines",
    "Singapore Airlines",
    "Qatar Airways",
    "Air France",
    "Cathay Pacific",
    "KLM Royal Dutch Airlines",
    "Turkish Airlines",
    "Etihad Airways",
    "American Airlines",
    "ANA All Nippon Airways",
    "Virgin Atlantic",
    "Swiss International Air Lines",
    "Air Canada",
    "Qantas",
    "Finnair",
    "Japan Airlines",
    "Air New Zealand",
    "EVA Air",
    "South African Airways",
    "Scandinavian Airlines",
    "Alitalia",
    "Austrian Airlines",
    "Hawaiian Airlines",
    "EgyptAir",
    "Gulf Air",
    "Iberia",
    "China Airlines",
    "Ethiopian Airlines",
    "SAS Scandinavian Airlines",
    "Brussels Airlines",
    "Vietnam Airlines",
    "LATAM Airlines",
    "LOT Polish Airlines",
    "Malaysia Airlines",
    "Philippine Airlines",
    "Royal Jordanian Airlines",
    "Air Astana",
    "Kenya Airways",
    "Air Mauritius",
    "Oman Air",
    "Pakistan International Airlines",
    "Saudi Arabian Airlines",
    "TAP Air Portugal",
    "Air China",
    "Air India",
    "Bangkok Airways",
    "Garuda Indonesia",
    "Korean Air",
    "SriLankan Airlines",
    "Xiamen Airlines",
    "AirAsia",
    "IndiGo",
    "Jetstar Airways",
    "Scoot",
    "Spring Airlines",
    "Vistara",
    "WestJet",
    "Air Arabia",
    "easyJet",
    "Ryanair",
    "Wizz Air",
    "Azul Brazilian Airlines",
    "JetBlue Airways",
    "Southwest Airlines",
    "Spirit Airlines",
    "Allegiant Air",
    "Frontier Airlines",
    "Sun Country Airlines",
    "Virgin America",
    "Flybondi",
    "Interjet",
    "VivaAerobus",
    "Volaris",
    "Aer Lingus",
    "Norwegian Air Shuttle",
    "TUI Airways",
    "flydubai",
    "AirAsia X",
    "AirAsia Zest",
    "Cebu Pacific",
    "Scoot Tigerair",
    "Tigerair",
    "S7 Airlines",
    "Ural Airlines",
    "Pobeda",
    "Azimuth",
    "Nordwind Airlines",
    "Globus Airlines",
    "Utair",
    "Somon Air",
    "Air Astana",
    "Qazaq Air",
    "SkyUp",
    "Air Serbia",
    "Ryanair Sun",
    "Wizz Air",
    "Eurowings",
    "Lauda",
    "Blue Air",
    "Flybondi",
    "JetSMART",
    "Norwegian Air Argentina",
    "FlyArystan",
    "IndiGo",
    "SpiceJet",
    "GoAir",
    "Vistara",
    "AirAsia India",
    "TruJet",
    "Star Air",
    "Zoom Air",
    "Air India Express",
    "Air Deccan",
    "Alliance Air",
    "Air Pegasus",
    "Air Odisha",
    "Nok Air",
    "Thai Vietjet Air",
    "VietJet Air",
    "Bamboo Airways",
    "Vietravel Airlines",
    "Pacific Airlines",
    "Vinpearl Air",
    "Cyprus Airways",
    "TAROM",
    "Blue Air",
    "Wizz Air",
    "Norwegian Air International",
    "Pegasus Airlines",
    "SunExpress",
    "Corendon Airlines",
    "AnadoluJet",
    "Turkish Airlines",
    "Freebird Airlines",
    "Onur Air",
    "Air Arabia",
    "Emirates",
    "flydubai",
    "Etihad Airways",
    "Air India Express",
    "IndiGo",
    "SpiceJet",
    "GoAir",
    "Vistara",
    "AirAsia India",
    "TruJet",
    "Star Air",
    "Zoom Air",
    "Air India",
    "Alliance Air",
    "Air Deccan",
    "Thai AirAsia",
    "Thai Smile",
    "Thai Lion Air",
    "Nok Air",
    "Thai Vietjet Air",
    "VietJet Air",
    "Bangkok Airways",
    "Thai Airways International",
    "Thai VietJet Air",
    "VietJet Air",
    "Bamboo Airways",
    "Vietravel Airlines",
    "Pacific Airlines",
    "Vinpearl Air",
    "Air Canada Rouge",
    "Air Transat",
    "Swoop",
    "Sunwing Airlines",
    "Flair Airlines",
    "WestJet Encore",
    "Porter Airlines",
    "Air North",
    "Canadian North",
    "Enerjet",
    "Ravn Alaska",
    "Sun Country Airlines",
    "Spirit Airlines",
    "Allegiant Air",
    "Frontier Airlines",
    "Southwest Airlines",
    "Alaska Airlines",
    "Hawaiian Airlines",
    "JetBlue Airways",
    "United Airlines",
    "American Airlines",
    "Delta Air Lines",
    "SkyWest Airlines",
    "Envoy Air",
    "Republic Airways",
    "Endeavor Air",
    "PSA Airlines",
    "Mesa Airlines",
    "Compass Airlines",
    "Horizon Air",
    "ExpressJet",
    "GoJet Airlines",
    "Air Wisconsin",
    "Trans States Airlines",
    "Cape Air",
    "Boutique Air",
    "Piedmont Airlines",
    "Silver Airways",
    "PenAir",
    "Contour Airlines",
    "Ultimate Air Shuttle",
    "Linear Air",
    "Southern Airways Express",
    "Surf Air",
    "Air Choice One",
    "Boutique Air",
    "Mokulele Airlines",
    "Hawaiian Airlines",
    "Southwest Airlines",
    "Allegiant Air",
    "American Airlines",
    "Delta Air Lines",
    "United Airlines",
    "JetBlue Airways",
    "Frontier Airlines",
    "Spirit Airlines",
    "Alaska Airlines",
    "Sun Country Airlines",
    "SkyWest Airlines",
    "Envoy Air",
    "Republic Airways",
    "PSA Airlines",
    "Mesa Airlines",
    "Compass Airlines",
    "Endeavor Air",
    "Horizon Air",
    "ExpressJet",
    "GoJet Airlines",
    "Air Wisconsin",
    "Trans States Airlines",
    "Cape Air",
    "Boutique Air",
    "PenAir",
    "Silver Airways",
    "Contour Airlines",
    "Southern Airways Express",
    "Ultimate Air Shuttle",
    "Linear Air",
    "Surf Air",
    "Air Choice One",
    "Boutique Air",
    "Mokulele Airlines"
]
